---
abstract: 'tie anonymous array, hash, etc. and return it'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Module::Build::Pluggable::CPANfile: 0.02
  Test::More: 0
  Tie::Array: 0
  Tie::Hash: 0
  Tie::Scalar: 0
configure_requires:
  Module::Build: 0.42
  Module::Build::Pluggable: 0.09
  Module::Build::Pluggable::CPANfile: 0.02
dynamic_config: 1
generated_by: 'Module::Build version 0.42, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Anon
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
  file:
    - README.pod
resources:
  bugtracker: https://github.com/debug-ito/Tie-Anon/issues
  repository: git://github.com/debug-ito/Tie-Anon.git
version: 0.01
